sonar.organization=eingram-homelab
sonar.projectKey=eingram-homelab_reusable-workflows

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./.github/workflows,./.github/actions