name: Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'projects/**/**/main.tf'

jobs:
  deploy:
    name: Deploy Terraform Project
    uses: eingram-homelab/.github/.github/workflows/terraform-deploy.yaml@main
    with:
      project_dir: 'projects/YOUR_TYPE/YOUR_PROJECT/'
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      GCP_STORAGE: ${{ secrets.GCP_STORAGE }}
