---
name: Workflows/Actions Validation

on:
  push:
    branches-ignore:
      - main

jobs:
  changes:
    name: Check for workflow or action file changes
    runs-on: arc-runners
    outputs:
      workflows: ${{ steps.changed.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Check for workflow file changes
        id: changed
        uses: tj-actions/changed-files@v47.0.6
        with:
          files: |
            .github/workflows/**/*.yaml
            .github/workflows/**/*.yml
            .github/actions/**/*.yaml
            .github/actions/**/*.yml

  gha-checks:
    name: GitHub Actions Workflow Checks
    needs: changes
    if: needs.changes.outputs.workflows == 'true'
    uses: ./.github/workflows/_gha-workflow-checks.yaml
